### ISSUE TITLE
Cannot deploy services (redis, rabbitmq, etc.) to a machine without deploying sensu configs to same machine

### ISSUE THREAD

**Issue by tculp** [cmacrae/ansible-sensu#109]
In tasks/main.yml, redis is deployed based on the following:
```
  - include: "{{ role_path }}/tasks/redis.yml"
    tags: redis
    when: redis_server
          and sensu_deploy_redis
    static: false
```
and in tasks/common.yml:
```
- name: Deploy Sensu Redis configuration
    template:
      dest: "{{ sensu_config_path }}/conf.d/redis.json"
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
      src: "{{ sensu_redis_config }}"
    when: sensu_deploy_redis
    notify:
      - restart sensu-server service
      - restart sensu-api service
      - restart sensu-enterprise service
      - restart sensu-client service
```
Both of these blocks depend on sensu_deploy_redis, so Redis cannot be deployed on a machine without the sensu config for redis also being deployed. In many cases, the redis server is not a sensu master, so this is unneccesary. Similar issues exist with sensu_deploy_rabbitmq.
