### ISSUE TITLE
Playbook crashes on CentOS if EPEL repo is not enabled

### ISSUE THREAD

**Issue by romainrbr** [cmacrae/ansible-sensu#126]
playbook.yaml : 

```
---
- name: create docker container
  hosts: localhost
  pre_tasks:
    - name: remove existing test container #hack because docker_container doesnt handle stopping and removing containers well
      shell: "docker kill {{ os_version }}-test-ansible"
      ignore_errors: yes
    - name: create docker container
      docker_container:
        name: "{{ os_version }}-test-ansible"
        image: "{{ os_version }}"
        command: sleep 300
        auto_remove: yes
        state: started
        recreate: yes

    - add_host:
        name: "{{ os_version }}-test-ansible"

- name: test against docker container
  hosts: all
  connection: docker
  roles:
    - cmacrae.sensu
  vars:
     - sensu_master: true
     - sensu_include_dashboard: true
     - rabbitmq_server: true
     - redis_server: true
     - dynamic_data_store: "./dynamic_data"
     - rabbitmq_host: "{{ os_version }}"
     - redis_host: "{{ os_version }}"
     - sensu_api_host: "{{ os_version }}"

```

ran with `ansible-playbook --extra-vars="os_version=centos" playbook.yml`

Will crash here : 
`TASK [cmacrae.sensu : Ensure redis is installed] ******************************************************************************************************************************************************************
fatal: [centos]: FAILED! => {"changed": false, "msg": "Error setting/accessing repos: Error getting repository data for epel, repository not found"}
	to retry, use: --limit @/tmp/ansible_test/playbook.retry
`

## How to fix : 
Either enable EPEL repo during the playbook, or add it to the `README.MD` as a dependency for CentOS, unsure which one is preferred.
