### ISSUE TITLE
client_definitions no longer looping

### ISSUE THREAD

**Issue by michaelpporter** [cmacrae/ansible-sensu#208]
I am not seeing this task execute anymore.

```yaml

- name: Deploy client definitions
  copy:
    src: "{{ static_data_store }}/sensu/client_definitions/{{ item }}/"
    dest: "{{ sensu_config_path }}/conf.d/{{ item | basename | regex_replace('.j2', '') }}"
    owner: "{{ sensu_user_name }}"
    group: "{{ sensu_group_name }}"
  when:
    - sensu_available_client_definitions is defined
    - sensu_available_client_definitions is not skipped
    - item in sensu_available_client_definitions.stdout_lines
  loop:
    - "{{ group_names|flatten }}"
  notify: restart sensu-client service

```

```bash
skipping: [apps-staging.example.com] => (item=['aperture', 'aperture-servers', 'internal', 'mysql', 'sensu', 'sensu_clients'])
skipping: [apps-test..example.com] => (item=['aperture', 'aperture-servers', 'internal', 'mysql', 'sensu', 'sensu_clients'])
skipping: [apps-03..example.com] => (item=['aperture', 'aperture-emea', 'mysql', 'production', 'sensu', 'sensu_clients', 'webchecks'])
skipping: [apps-04..example.com] => (item=['aperture', 'aperture-prod', 'mysql', 'production', 'sensu', 'sensu_clients'])
skipping: [apps-demo..example.com] => (item=['aperture', 'aperture-demo', 'mysql', 'production', 'sensu', 'sensu_clients'])
skipping: [prod-mysql-01..example.com] => (item=['mysql', 'production', 'sensu', 'sensu_clients'])
```
