### ISSUE TITLE
Removing node from group does not remove client definitions (standalone)

### ISSUE THREAD

**Issue by michaelpporter** [cmacrae/ansible-sensu#210]
https://ansible-sensu.readthedocs.io/en/latest/dynamic_checks/
> The same goes for the removal of a node from a group. Did you just realize you really don't want mime.domain.name to act as a redis server? It's cool, we all make mistakes, just take him out of the [sensu_redis_servers] group in your inventory. When your play comes through again, applying this Sensu role, he'll be unsubscribed from the sensu_redis_servers stream, and redis'll stop being monitored!

Inventory

```ini
[test]
sensu-client.example.com
sensu.example.com
```

data/static
```
-- sensu
    |-- client_definitions
    |   |-- test
    |   |   `-- check_users.json.j2
```

Run the playbook
`ansible-playbook sensu.yml --tags plugins` or
`ansible-playbook sensu.yml --limit sensu-client.example.com,sensu.example.com`

sensu-client.example.com
```bash
ls -l /etc/sensu/conf.d
-- test
```
sensu.example.com
```bash
ls -l /etc/sensu/conf.d
-- test
```

Update inventory

```ini
[test]
sensu-client.example.com
```

data/static
```
-- sensu
    |-- client_definitions
    |   |-- test
    |   |   `-- check_users.json.j2
```

Run the playbook
`ansible-playbook sensu.yml --limit sensu-client.example.com,sensu.example.com`

sensu-client.example.com
```bash
ls -l /etc/sensu/conf.d
-- test
```
sensu.example.com
```bash
ls -l /etc/sensu/conf.d
-- test
```

Client definitions are still on the host.

I can not think of a way to cleanup the client definitions without removing all `client_definitions` folders from each host on each run...

Perhaps a `cleanup tag`

```yaml
- name: Register available client definitions
  command: "ls {{ static_data_store }}/sensu/client_definitions"
  delegate_to: localhost
  register: sensu_available_client_definitions
  changed_when: false
  become: false

- name: Cleanup client definitions
  copy:
    src: "{{ static_data_store }}/sensu/client_definitions/{{ item }}/"
    dest: "{{ sensu_config_path }}/conf.d/{{ item | basename | regex_replace('.j2', '') }}"
   state: absent
  when:
    - sensu_cleanup_client_definitions
    - sensu_available_client_definitions is defined
    - sensu_available_client_definitions is not skipped
    - item in sensu_available_client_definitions.stdout_lines
  loop: "{{ group_names|flatten }}"
  notify: restart sensu-client service
```

`ansible-playbook sensu.yml --extra-vars sensu_cleanup_client_definitions=true`

Even so, the checks would need to be removed from Redis else they will timeout. The extreme method, `/usr/bin/redis-cli flushdb`. You loose history of checks and could cause alerts to be resent if you are not in a good state.
