### ISSUE TITLE
Look at using `with_file_glob` and filters instead of shell execution for definition deployment

### ISSUE THREAD

**Issue by cmacrae** [cmacrae/ansible-sensu#3]
[This](https://github.com/cmacrae/ansible-sensu/blob/master/tasks/plugins.yml#L71) can probably be achieved using `with_file_glob` and Jinja filters:

``` yaml
  - name: Deploy check/handler/filter/mutator definitions to the master
    template:
      src: "{{ static_data_store }}/sensu/definitions/{{ item }}.j2"
      dest: "{{ sensu_config_path }}/conf.d/{{ item }}"
      owner: "{{ sensu_user_name }}"
      group: "{{ sensu_group_name }}"
    when: sensu_master
    with_lines:
      - ls {{ static_data_store }}/sensu/definitions | sed 's/\.j2//'
    notify: restart sensu-server service
```
