### ISSUE TITLE
Cannot override any redis related variable

### ISSUE THREAD

**Issue by gcmalloc** [cmacrae/ansible-sensu#31]
The `include_vars` module override any existing variable. I wanted to override the redis repo, but couldn't do so.

**Comment by smuth4** [comment]
I don't think there's an easy way to solve this, although you can work around it with the `-e` flag, which always "wins" in terms of variable precedence.

**Comment by davidschroeder** [comment]
You can override the role variables by setting facts.  For example, I override redis_pkg_repo and redis_service_name in my playbook:

```
---
- name: Standalone Sensu Server
  hosts: sensu_masters
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    dynamic_data_store: "data"
    sensu_include_plugins: false
    sensu_deploy_rabbitmq: true
    sensu_deploy_redis: true
    rabbitmq_server: true
    redis_server: true
  pre_tasks:
    - name: Add alternate RabbitMQ APT repo GPG key
      apt_key:
        url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
        state: present
    - name: Fix redis repo
      set_fact:
        redis_pkg_repo: 'ppa:chris-lea/redis-server'
        redis_service_name: redis-server
  roles:
    - { role: sensu-ansible, sensu_master: true, sensu_include_dashboard: true }
```
