### ISSUE TITLE
ssl_generate.yml 

### ISSUE THREAD

**Issue by sqanto** [cmacrae/ansible-sensu#42]
Maybe its the same problem : ssl download error #41

fatal: [xxxx.xxxx.xxxx]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /etc/sensu/ssl_generation not writable"}

**Comment by sqanto** [comment]
maybe its help ? 

```
- name: Untar the ssl_certs tarball from sensuapp.org
  unarchive:
  args:
     src: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool.tar"
     dest: "{{ sensu_config_path }}/ssl_generation/"
     copy: no  <---- Option
     creates: "{{ sensu_config_path }}/ssl_generation/sensu_ssl_tool"
```
