### ISSUE TITLE
AnsibleUndefinedVariable: 'dict object' has no attribute 'rabbitmq_servers'

### ISSUE THREAD

**Issue by deadghost** [cmacrae/ansible-sensu#8]
`ansible 2.0.1.0`
`ubuntu 14.04`

Running the play with defaults:

```
- name: Install and config sensu stack.
  hosts: prod
  become: true
  become_method: sudo
  roles:
    - role: cmacrae.sensu
```

`$ ansible-playbook prod/sensu.yml`

Things of note:

```
TASK [cmacrae.sensu : Deploy the Sensu client SSL cert/key] ********************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this 
will be a fatal error.. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

TASK [cmacrae.sensu : Deploy Sensu client RabbitMQ configuration] **************
fatal: [kimsufi]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'rabbitmq_servers'"}
```

The warning `undefined Error` is not helpful so I'm stuck as to how to resolve it and whether it is causing the failure down the chain. Any ideas?
