### ISSUE TITLE
prerequisite of plugins

### ISSUE THREAD

**Issue by roumano** [cmacrae/ansible-sensu#93]
Hi,

it's will great if prerequisite of plugins is managed by the role

i think, it's can be, only, construct empirically...
for exemple, postgres plugins (if i have add these in plugins.yml) (maybe it's for only when: ansible_os_family == 'RedHat'
  : 
```
  - name: Define pre-requisite of each plugins
    set_fact:
      package_needed: "{{ package_needed | default([]) }} + [ 'postgresql-devel' ]"
    when: "'postgres' in sensu_remote_plugins"

  - name: Install pre-requisite of each plugins
    package:
      name: "{{ item }}"
    with_items: "{{ package_needed | default([]) }}"
```
